### ISSUE TITLE
16.0.0 support

### ISSUE THREAD

**Issue by djskual** [XorTroll/emuiibo#229]
switch crash loading emuiibo overlay on 16.0.0 ams 1.5.0
thx

**Comment by urherenow** [comment]
Just had an adventure compiling myself. Built with latest libnx installed and libtesla with required change. This is untested by me, so please backup your files before trying, and please let me know if this worked.
[emuiibo.zip](https://github.com/XorTroll/emuiibo/files/10825116/emuiibo.zip)

**Comment by djskual** [comment]
i will test, but can't get it to compile on my side.
i get some error while compiling nsp

**Comment by djskual** [comment]
Building and generating NSP...
Triple: aarch64-nintendo-switch
error: failed to run `rustc` to learn about target-specific information

Caused by:
  process didn't exit successfully: `rustc - --crate-name ___ --print=file-names --target aarch64-ni
ntendo-switch --crate-type bin --crate-type rlib --crate-type dylib --crate-type cdylib --crate-type
 staticlib --crate-type proc-macro --print=sysroot --print=cfg` (exit code: 1)
  --- stderr
  error: Error loading target specification: invalid escape at line 10 column 26. Run `rustc --print
 target-list` for a list of built-in targets

**Comment by djskual** [comment]
please could you contact me and explain to me what i need to done on my rust install to get this to compile. thx

**Comment by urherenow** [comment]
Did you update your Tesla menu?

**Comment by alula** [comment]
You need to install cargo-nx and use nightly compiler and it will build just fine

**Comment by North-West-Wind** [comment]
I can't compile `nx`. It kept shouting errors at me during `cargo nx build --release`.

```
error: instruction requires: sha2
   --> /home/northwestwind/.cargo/git/checkouts/nx-3560396e08328007/5506c73/src/crypto/sha256.rs:196:18
    |
196 |                 "sha256h2 {cur_hash1:q}, {tmp_hash:q}, {tmp3:v}.4s",
    |                  ^
    |
note: instantiated into assembly here
   --> <inline asm>:105:1
    |
105 | sha256h2 q18, q19, v6.4s
    | ^
```

All errors looked like this, except in different lines and `sha2` is sometimes `aes`

**Comment by ProfessorDeez** [comment]
I tried to compile it with the `cargo nx build` command and it gave me this [error](https://github.com/XorTroll/emuiibo/files/10830422/error.txt).

When I typed the `cargo nx --version` command it said ``cargo-nx 0.2.0``. I was able to compile something else with the `cargo nx build` command without any errors.

**Comment by urherenow** [comment]
It was changed to 0.2.0 several hours ago. I swear, I had no issue last night building this but cargo-nx was 0.1.0. Best to create issues there, I think… unless emuibo needs updating to match cargo-nx changes.

I have these same errors on a different vm I just tried it on (mostly noticed aes errors on my screen)

**Comment by North-West-Wind** [comment]
Thanks @urherenow I'm gonna try compiling it again

**Comment by djskual** [comment]
Same error here

**Comment by North-West-Wind** [comment]
I compiled it and placed it correctly in my SD card, but now the sysmodule refuses to start
![image](https://user-images.githubusercontent.com/45654842/221349147-0505d96e-9711-4575-bb21-b62c977a903a.png)

**Comment by djskual** [comment]
> I compiled it and placed it correctly in my SD card, but now the sysmodule refuses to start ![image](https://user-images.githubusercontent.com/45654842/221349147-0505d96e-9711-4575-bb21-b62c977a903a.png)

What had you done to fix crypto errors?

**Comment by North-West-Wind** [comment]
@djskual I installed the older version (0.1.0 to be specific) of cargo-nx by `cargo install cargo-nx --git https://github.com/aarch64-switch-rs/cargo-nx --rev 78ab075`

**Comment by djskual** [comment]
@North-West-Wind ok, thanks, but now, i get the error i got yersteday and can't compile....
[https://github.com/XorTroll/emuiibo/issues/229#issuecomment-1443765978](https://github.com/XorTroll/emuiibo/issues/229#issuecomment-1443765978)

**Comment by XorTroll** [comment]
Be a bit more patient, I'm still fixing this

**Comment by North-West-Wind** [comment]
> @North-West-Wind ok, thanks, but now, i get the error i got yersteday and can't compile.... [#229 (comment)](https://github.com/XorTroll/emuiibo/issues/229#issuecomment-1443765978)


I'm not a professional at rust, nor do I know how to troubleshoot, so I will just leave you with the things I went through:

- `rustup toolchain install nightly`: Installs the nightly toolchain.
- `rustup default nightly`: Sets nightly as the default toolchain.
- `git clone https://github.com/XorTroll/emuiibo --recurse-submodules && cd emuiibo`: Clones this repo and move into it.
- `cargo install cargo-nx --git https://github.com/aarch64-switch-rs/cargo-nx --rev 78ab075`: Installs cargo-nx 0.1.0
- `make all`: Compiles everything and they will be put into SdOut.

> Be a bit more patient, I'm still fixing this

Thanks and good luck! We will be waiting.

**Comment by alula** [comment]
> I compiled it and placed it correctly in my SD card, but now the sysmodule refuses to start
> 
> ![image](https://user-images.githubusercontent.com/45654842/221349147-0505d96e-9711-4575-bb21-b62c977a903a.png)
> 
> 

Try with my PR that was just merged

**Comment by djskual** [comment]
@alula 
i compiled the libnx for 16.0.0 from atmosphere github, compiled ovlloader, tesla menu, emuiibo with the last merge.
Got crash on console booting.

**Comment by alula** [comment]
![](https://media.discordapp.net/attachments/489123163330838529/1079183391355850752/IMG_20230226_002906.jpg)

Are you sure you don't have any extra incompatible sysmodules or other things installed?

**Comment by djskual** [comment]
ok, i will all recompile, nothing else install, fresh 16.0.0 on emunand

**Comment by urherenow** [comment]
If you've deleted your old atmosphere folder while trying to get things to work, did you re-create the various config files? Without config files, Atmosphere's default behavior is to automatically enable all cheats. A bad combination of cheats could be crashing or locking your system...

**Comment by urherenow** [comment]
> Try with my PR that was just merged, was some debugging code that caused a panic

When I build the latest commit (which also builds in msys2's mingw64 now, by the way, and cargo 0.2.0 on both msys and Ubuntu, so thanks XorTroll!) I get a panic on boot: 2168-0000 (0xa8) if the boot2 flag is set. If it is not set, the tesla menu opens and shows amuiibo... but says it isn't present when I try to open it.

FYI, I renamed my atmosphere/contents folder, and made a new one with ONLY tesla and emuiibo in it (0100000000000352 and 420000000007E51A)

**Comment by North-West-Wind** [comment]
The latest commit ([c15d39d](https://github.com/XorTroll/emuiibo/commit/c15d39d653580313306a222ea26d93feacaf61b9)) just crashes on boot

**Comment by djskual** [comment]
same thing here. ERROR CODE 2168-0000 (0xa8)
ovlloader & ovlmenu work fine, but if i add emuiibo, crash on switch boot.
16.0.0 ams 1.5.0|E

**Comment by josete2k** [comment]
Solved with last editing form XorTroll

**Comment by josete2k** [comment]
![2023022621430900](https://user-images.githubusercontent.com/561354/221436143-eb817c7e-5608-444d-a2fa-ff4f569ba5fb.jpg)

**Comment by josete2k** [comment]
![2023022621430900](https://user-images.githubusercontent.com/561354/221436490-50fe511e-916e-46c7-8723-00cc89c05d35.jpg)

**Comment by urherenow** [comment]
wait, which editing? I don't see any commits after the one that fixed building. It no longer crashes for me though, so something must have changed. But... I still get a blank menu that says "emuiibo doesn't seem to be present"

**Comment by josete2k** [comment]
> wait, which editing? I don't see any commits after the one that fixed building. It no longer crashes for me though after building again, so something must have changed. But... I still get a blank menu that says "emuiibo doesn't seem to be present"

https://github.com/aarch64-switch-rs/nx
https://github.com/aarch64-switch-rs/nx/commit/6f2e75178c31b5db1c5835c99b8ac95d1805b526

reinstall your cargo nx

cargo install cargo-nx --git https://github.com/aarch64-switch-rs/cargo-nx

**Comment by urherenow** [comment]
done. but still... emuiibo doesn't seem to be present. I feel like I'm missing something stupid. Have to go to work now...

**Comment by josete2k** [comment]
Are you making all?

Here's my compilation:

[emuiibo-v0.6.5.zip](https://github.com/XorTroll/emuiibo/files/10834884/emuiibo-v0.6.5.zip)

**Comment by djskual** [comment]
same here, with last commit, no crash on boot. but when i click on emuiibo in the teslamenu, that say to me that emuiibo seem to be not present....
Don't understand where is the mistake. i want to know....
i will make all instead just make.
thx for you compilation

**Comment by josete2k** [comment]
Hmmm...

Have you updated your libnx for 16.0.0 support?

You know:

git clone --recursive https://github.com/Atmosphere-NX/libnx
cd libnx
git checkout 1600_support
make
make install

**Comment by djskual** [comment]
yes, it's done.
humm, i've modified the makefile of overlay to have v 0.6.5 instead of v1.0.0
will revert and recompile...

**Comment by josete2k** [comment]
If you do that, there is a version mismatch...

**Comment by djskual** [comment]
sure it's the problem... recompiling libnx to be sure

**Comment by djskual** [comment]
Recompiled... Same result with 1.0.0 version. will  test your compile... perhaps it's due to my atmosphere

**Comment by djskual** [comment]
same with you compiled files. and your emuiibo write 0.6.5 in tesla menu... as mine before. had you modified somthing else than in the overlay makefile?

**Comment by josete2k** [comment]
Yes, main in emuiibo folder.

Do you have last ovlmenu?

https://github.com/proferabg/EdiZon-Overlay/releases/download/v1.0.4/ovlmenu.ovl

**Comment by djskual** [comment]
i have compiled ovlmenu myself with last libtesla and libnx16.0.0
yes i restart each time i remove my sd to put in my pc

i will make a fresh install of atmosphere and patches

**Comment by djskual** [comment]
ok, same with a fresh install, iv'tried the ovlmenu from edizon but same result
each time i done new compile, i delete all files and copy all new files.

also, you edited overlay make file and main in emuiibo?

**Comment by urherenow** [comment]
since a few commits were done to 1600_support since I last built atmosphere, I updated and reinstalled it. Just for grins and to be 100% sure, I rebuilt Tesla menu, ovlloader, and emuiibo. Still the same. Says "emuiibo doesn't seem to be present" right underneath the title. Only noticeable errors are a buttload of unused variables (some of which sound important to me) in bin.rs.

And finally, I rebuilt emutool myself, created 1 amiibo, and placed only that amiibo in the directory.

As a side note... there is already an emutool on github for managing an emunand. Can't we think of a better name for this? Like emuiibotool? Or amiitool, if you really care about 8.3  filenames?

**Comment by urherenow** [comment]
What about "Still the same. Says "emuiibo doesn't seem to be present" right underneath the title", don't you understand?

**Comment by djskual** [comment]
> What about "Still the same. Says "emuiibo doesn't seem to be present" right underneath the title", don't you understand?

Sorry!!! as after this you wrote about emutool and amibo... just want to be sure. sorry...

**Comment by toxin-x** [comment]
i'm having the same issue with the emuiibo sysmodule not turning on. is there some sort of logs i can read or send?

**Comment by Kisora1** [comment]
> i'm having the same issue with the emuiibo sysmodule not turning on. is there some sort of logs i can read or send?

I'm also having the exact same issue

**Comment by qhq** [comment]
me too "emuiibo doesn't seem to be present"

**Comment by josete2k** [comment]
Some gbatemp users have tested the compilation I've uploaded with my compiled atmosphere and config files with success.

So the issue is maybe with config or with pre-release.


Please, turn off the autoload cheats and test.


I can provide the atmos pack but it has sigpatches and I don't want to generate conflicts with the repository.


If you want test, please sen me a PM in gbatemp.

**Comment by urherenow** [comment]
I just tested with nothing in contents, other than ovlloader and emuiibo. .overlays has ONLY ovlmenu.ovl and 1_emuiibo.ovl, all from the pack you PMed me.

100% nothing to do with cheats.

**Comment by josete2k** [comment]
But emuiibo has a contents folder...

**Comment by urherenow** [comment]
Umm… yea? That’s what I said. Ovlloader, and emuiibo in the contents. Nothing else to interfere.

**Comment by josete2k** [comment]
> Umm… yea? That’s what I said. Ovlloader, and emuiibo in the contents. Nothing else to interfere.

It's a poltergeist so 🤣🤣🤣

**Comment by josete2k** [comment]
[SdOut.zip](https://github.com/XorTroll/emuiibo/files/10855677/SdOut.zip)
Same with this I guess...

I'm testing with another switch and it seems that it doesn't work

**Comment by North-West-Wind** [comment]
> I'm testing with another switch and it seems that it doesn't work

Wow. This issue has gotten so much more complicated.

**Comment by josete2k** [comment]
More tests.


SD1 working in emummc in switch1
SD1 working in sysmmc in switch1

SD2 not working in emummc in switch2
SD2 not working in sysmmc in switch2

But...

SD1 WORKING in sysmmc in switch 2.

So, even the files in sd1 and SD2 are the same... SD1 is working in both consoles.

Any kind of hidden file maybe?

**Comment by Masamune3210** [comment]
Tried fully formatting the card? Maybe some latent filesystem corruption

**Comment by North-West-Wind** [comment]
Thanks for the idea. You reminded me I formatted my SD card to exFAT. I'm testing to see if that's the issue.

**Comment by 1332348216** [comment]
After testing, the same atmosphere, some people's emuiibo can not be found, some people can use it normally。
Edizon was the same

**Comment by djskual** [comment]
Compiled my own Atmosphere and Patches.
Same result!!! Not working...

**Comment by josete2k** [comment]
I I solved the issue.

Disabling/enabling emuiibo from Edizon SE makes the plugin working...

**Comment by djskual** [comment]
> I think I solved the issue.
> 
> Disabling/enabling emuiibo from Edizon SE makes the plugin working...
> 
> Hekate toolbox maybe works too.
> 
> The ovl sysmodules doesn't even with a new compilation.

where do you find edison se for 16.0.0 ?
i will try.

**Comment by josete2k** [comment]
Worked once... now it doesn't work...

I'm tired...

**Comment by djskual** [comment]
> Worked once... now it doesn't work...
> 
> I'm tired...

edisonSE tips didn't work for me :(

**Comment by impeeza** [comment]
You should continue this on gbatemp. There you will find edizon for 16.0.0 and answer for the problem

**Comment by Vorffeed** [comment]
> I think I solved the issue.
> 
> Disabling/enabling emuiibo from Edizon SE makes the plugin working...
> 
> Hekate toolbox maybe works too.
> 
> The ovl sysmodules doesn't even with a new compilation.

I don't see anything like that in the edizon ovl?

**Comment by urherenow** [comment]
It's not in the ovl, it's in the app. But it doesn't work for me. select enable, and you get a message stating that you must restart, but when I restart, it's disabled again. What is actually happening when you "enable" a sys module with Edison? 


I see no working answer on gbatemp.

**Comment by Vorffeed** [comment]
> It's not in the ovl, it's in the app. But it doesn't work for me. select enable, and you get a message stating that you must restart, but when I restart, it's disabled again. What is actually happening when you "enable" a sys module with Edizon?
> 
> I see no working answer on gbatemp.

could you pass some screenshot of where it is because in the application I only see the icons of the games xd

**Comment by urherenow** [comment]
Press L

**Comment by Vorffeed** [comment]
No way, emuiibo always starts on off xd

**Comment by josete2k** [comment]
ok...

New way.

Delete all your Mii.

**Comment by toxin-x** [comment]
deleting my mii worked! strange

**Comment by Vorffeed** [comment]
I wonder, and instead of deleting the mii from the console, couldn't I delete the code to dumpear the mii from emuiibo?????

**Comment by josete2k** [comment]
> I wonder, and instead of deleting the mii from the console, couldn't I delete the code to dumpear the mii from emuiibo?????

Sure, XorTroll will fix it!

**Comment by Vorffeed** [comment]
I just realized that the dumpeo it makes is blank from the mii-charinfo.bin file in the emuiibo/miis/0 folder.

**Comment by North-West-Wind** [comment]
> I wonder, and instead of deleting the mii from the console, couldn't I delete the code to dumpear the mii from emuiibo?????

@josete2k @Vorffeed Thank you so much

I tried your theory and this is totally it. I just made [a fork](https://github.com/North-West-Wind/emuiibo) and [disabled the Mii extraction part](https://github.com/North-West-Wind/emuiibo/commit/4c086609af5ab7066971ca4dfa947013627a2bcc). Now it is working!

I will not make a PR of it though because fixing it by disabling a feature doesn't seem like a long term solution.

Here's the compiled edited emuiibo sysmodule (you don't have to delete your Miis): 
[SdOut.zip](https://github.com/XorTroll/emuiibo/files/10876943/SdOut.zip)

![IMG_20230303_083035](https://user-images.githubusercontent.com/45654842/222601149-4a282ac2-ab15-4d0d-9044-29826cd8e196.jpg)

**Comment by Vorffeed** [comment]
> > Me pregunto, y en vez de borrar el mii de la consola no podria borrar el codigo para dumpear el mii de emuiibo?????
> 
> @josete2k @Vorffeedmuchas gracias
> 
> Probe tu teoria y esto es totalmente. Acabo de hacer [una bifurcación](https://github.com/North-West-Wind/emuiibo) y [deshabilité la parte de extracción de Mii](https://github.com/North-West-Wind/emuiibo/commit/4c086609af5ab7066971ca4dfa947013627a2bcc) . ¡Ahora está funcionando! Sin embargo, no haré relaciones públicas porque solucionarlo deshabilitando una función no parece una solución a largo plazo.
> 
> Aquí está el módulo del sistema emuiibo compilado y editado (no es necesario que elimine su Miis): [SdOut.zip](https://github.com/XorTroll/emuiibo/files/10876943/SdOut.zip)
> 
> ![IMG_20230303_083035](https://user-images.githubusercontent.com/45654842/222601149-4a282ac2-ab15-4d0d-9044-29826cd8e196.jpg)

Thank you very much, it is working 

![2023 03 02_133948](https://user-images.githubusercontent.com/10000442/222603136-675cb3bb-9145-48c2-ad0c-e3d0ab32a72d.jpg)

**Comment by urherenow** [comment]
Still not working for me. deleted all folders relating to Edizon-se, and reinstalled it/breeze. Installed the last ovlmenu.ovl posted above... which is confusing because the directory suggests it's the latest Edizon overlay. ovlmenu should be testla. I even deleted my mii before I saw that last attachment with it commented out (but I'm trying that attachment anyway).

Edizon-se still says it's off whenever I set it to on -> exit -> then open the sysmodules manager again. Setting it to on, rebooting, then trying again is the same. Isn't the boot2.flag supposed to load it? Again, what actually happens when you turn on a sysmodule there? Does it just add a boot2.flag or what?

**Comment by Kisora1** [comment]
Nothing is working for me :c

**Comment by North-West-Wind** [comment]
It probably has nothing to do with overlay since it only acts as a GUI.

Also, sidenote, to enable emuiibo logs, create an empty file `sdmc:/emuiibo/flags/log.flag`

**Comment by urherenow** [comment]
Lol… nice thought, but what would a log do if the thing never loads? I had that file, before switching to the latest stuff posted here, but it was blank.

**Comment by jackwaecow** [comment]
> It probably has nothing to do with overlay since it only acts as a GUI.
> 
> Also, sidenote, to enable emuiibo logs, create an empty file `sdmc:/emuiibo/flags/log.flag`

hey NW wind, by anychance we can chat on discord?Ash__#2573

**Comment by North-West-Wind** [comment]
> Lol… nice thought, but what would a log do if the thing never loads? I had that file, before switching to the latest stuff posted here, but it was blank.

That `log.flag` file is supposed to be blank. Even if it doesn't load, I want to see if it will at least output something before dying.

**Comment by urherenow** [comment]
Nope. 

IT. NEVER. LOADS.

**Comment by jackwaecow** [comment]
If anyone has it working, please send me the tesla, emuiibo and whatever related file that works to me. Much appreciated

**Comment by jackwaecow** [comment]
> Nope.
> 
> IT. NEVER. LOADS.
> 
> anyway, I’m done with this. I just make stickers with thenaya on my 3ds anyway.

do you have emuiibo in edizon sysmodule turned on?

**Comment by jackwaecow** [comment]
One thing confirmed is that NW's regular switch works while my OLED doesn't

**Comment by urherenow** [comment]
I’ve been smart and have not upgraded my OLED. I’ve only been playing with this on an original, launch-day Switch. And it doesn’t work on it. I can repeatedly “turn it on” in Edizon-SE, and it always reverts to off. It never loads, just as I said already. Nobody has even been able to explain exactly what Edizon is actually  (supposed to be) doing when you “turn on” a sysmodule.

**Comment by josete2k** [comment]
> I’ve been smart and have not upgraded my OLED. I’ve only been playing with this on an original, launch-day Switch. And it doesn’t work on it. I can repeatedly “turn it on” in Edizon-SE, and it always reverts to off. It never loads, just as I said already. Nobody has even been able to explain exactly what Edizon is actually (supposed to be) doing when you “turn on” a sysmodule.

Edizon places or deletes the boot2.flag.


Go to 15.0.1 and update to 16.0.0 once you have emuiibo 0.6.4 working

**Comment by urherenow** [comment]
If that’s all it does, then it’s useless. The boot2.flag has been there from the start. It just doesn’t load. Sunday evening when I’m back home, I’ll delete all of the error reports from Atmosphere and see if it generates something there on boot.

**Comment by North-West-Wind** [comment]
> I’ve been smart and have not upgraded my OLED. I’ve only been playing with this on an original, launch-day Switch. And it doesn’t work on it. I can repeatedly “turn it on” in Edizon-SE, and it always reverts to off. It never loads, just as I said already. Nobody has even been able to explain exactly what Edizon is actually (supposed to be) doing when you “turn on” a sysmodule.

If that's the case, I recommend opening a new issue about that. This is beyond the scope of 16.0.0 support.

**Comment by urherenow** [comment]
Dude… this is exactly 16.0.0 support. It’s only on 16.0.0 that it happens. But I already said I didn’t care and I’m done with this, so stop quoting/pinging me, and I’ll be happy to not add to this shitshow of an issue again. 

Thenaya and NFC stickers FTW

**Comment by josete2k** [comment]
> Dude… this is exactly 16.0.0 support. It’s only on 16.0.0 that it happens. But I already said I didn’t care and I’m done with this, so stop quoting/pinging me, and I’ll be happy to not add to this shitshow of an issue again.
> 
> Thenaya and NFC stickers FTW

Check your gbatemp messages, please...

**Comment by djskual** [comment]
> > I wonder, and instead of deleting the mii from the console, couldn't I delete the code to dumpear the mii from emuiibo?????
> 
> @josete2k @Vorffeed Thank you so much
> 
> I tried your theory and this is totally it. I just made [a fork](https://github.com/North-West-Wind/emuiibo) and [disabled the Mii extraction part](https://github.com/North-West-Wind/emuiibo/commit/4c086609af5ab7066971ca4dfa947013627a2bcc). Now it is working! I will not make a PR of it though because fixing it by disabling a feature doesn't seem like a long term solution.
> 
> Here's the compiled edited emuiibo sysmodule (you don't have to delete your Miis): [SdOut.zip](https://github.com/XorTroll/emuiibo/files/10876943/SdOut.zip)
> 
> ![IMG_20230303_083035](https://user-images.githubusercontent.com/45654842/222601149-4a282ac2-ab15-4d0d-9044-29826cd8e196.jpg)

Not working for me. same result.
tested your SdOut et done files by my side too.
recompiled atmosphere, hbl, hbmenu, ovlloader, teslamenu, emuiibo with last libnx changes (today 3 more changes)
hope someone will find the problem.

**Comment by josete2k** [comment]
> > > I wonder, and instead of deleting the mii from the console, couldn't I delete the code to dumpear the mii from emuiibo?????
> > 
> > 
> > @josete2k @Vorffeed Thank you so much
> > I tried your theory and this is totally it. I just made [a fork](https://github.com/North-West-Wind/emuiibo) and [disabled the Mii extraction part](https://github.com/North-West-Wind/emuiibo/commit/4c086609af5ab7066971ca4dfa947013627a2bcc). Now it is working! I will not make a PR of it though because fixing it by disabling a feature doesn't seem like a long term solution.
> > Here's the compiled edited emuiibo sysmodule (you don't have to delete your Miis): [SdOut.zip](https://github.com/XorTroll/emuiibo/files/10876943/SdOut.zip)
> > ![IMG_20230303_083035](https://user-images.githubusercontent.com/45654842/222601149-4a282ac2-ab15-4d0d-9044-29826cd8e196.jpg)
> 
> Not working for me. same result. tested your SdOut et done files by my side too. recompiled atmosphere, hbl, hbmenu, ovlloader, teslamenu, emuiibo with last libnx changes (today 3 more changes) hope someone will find the problem.

I didn't have it working until I placed old emuiibo files and check that emuiibo sysmodule is in ON (ovl-sysmodules).

Then I replaced files with the new compilation.

**Comment by josete2k** [comment]
So the point is

Remove Miis
Update to 16.0.0 
Place emuiibo 0.6.4
Add ovlmenu.ovl from Edizon-SE fork (16.0.0) 
Activate old emuiibo sysmodule
Check that it is active (you can use ovl-sysmodules)
Replace files with the new compilation

It's crazy XD but it works XD

**Comment by Vorffeed** [comment]
> [North-West-Wind](/North-West-Wind)

I haven't done any of that, I just use Edizone's ovlmenu.ovl and ovlSysmodules updated to 16.0 and @North-West-Wind's folder, having updated to 16.0 without deleting any previous folders.

**Comment by North-West-Wind** [comment]
Xor just dropped a new commit and provided a dev build on Discord. He said he found the underlying issue and fixed it so please have a try.

**Comment by XorTroll** [comment]
You guys had to be a bit more patient, I'm a bit busy but I can fix things when I have some time
I'd suggest any interested people to join the Discord, since this upcoming new release is a big one (all the changes already in progress before 16.0.0), I share test builds there and testing is always really helpful

**Comment by josete2k** [comment]
> You guys had to be a bit more patient, I'm a bit busy but I can fix things when I have some time I'd suggest any interested people to join the Discord, since this upcoming new release is a big one (all the changes already in progress before 16.0.0), I share test builds there and testing is always really helpful

You're the man. Thanks

What's the discord channel?

**Comment by XorTroll** [comment]
https://discord.gg/3KpFyaH

**Comment by josete2k** [comment]
> https://discord.gg/3KpFyaH

Thanks again

I can confirm that emuiibo is working (16.0.0) compiling with the new sources.

**Comment by Bushido1992** [comment]
i found out, that the "miis" folder inside /emuiibo is not there and thats why it not work / not load. After create the emuiibo/miis folder it works. See it as a quick fix

**Comment by urherenow** [comment]
> i found out, that the "miis" folder inside /emuiibo is not there and thats why it not work / not load. After create the emuiibo/miis folder it works. See it as a quick fix. But it´s better to wait for official release from Xor

This was totally it for me. Good find! I'm sure the code fix is just a line or two as well...

**Comment by Alvarden15** [comment]
> > https://discord.gg/3KpFyaH
> 
> Thanks again
> 
> I can confirm that emuiibo is working (16.0.0) compiling with the new sources.
> 
> I'm uploading it as a hotfix...
> 
> [emuiibo-v0.6.5.zip](https://github.com/XorTroll/emuiibo/files/10892346/emuiibo-v0.6.5.zip)

Ok, that actually work. Thank you!

**Comment by lookye** [comment]
Latest release got support for you guys.
